### ISSUE TITLE
Only the first element of the option COURSE_LIST in config.ini is selected

### ISSUE THREAD

**Issue by qqq89513** [ghnmqdtg/Course-Snatching-Selenium#1]
If I have config.ini like this:
```ini
...
[COURSE]
COURSE_LIST = ["ET3004701", "ET4001701", "PE113A050"]
...
```
Then only the first course "ET3004701" is selected:
![image](https://user-images.githubusercontent.com/35174145/93107412-24499580-f6e4-11ea-87dc-47b0484db58f.png)

It is because [main.py: L20](https://github.com/ghnmqdtg/Course-Snatching-Selenium/blob/85ed832393c6dc74eddb61933d20dd428f02e96c/main.py#L20) is executed only once.

**Comment by ghnmqdtg** [comment]
Thanks for the correction.
Variable "COURSENO" in main.py: L20 is a global variable, it should be put into the while loop in "snatch" function.
